#!/bin/sh

increment_version ()
{
  declare -a part=( ${1//\./ } )
  declare    new
  declare -i carry=1

  for (( CNTR=${#part[@]}-1; CNTR>=0; CNTR-=1 )); do
    len=${#part[CNTR]}
    new=$((part[CNTR]+carry))
    [ ${#new} -gt $len ] && carry=1 || carry=0
    [ $CNTR -gt 0 ] && part[CNTR]=${new: -len} || part[CNTR]=${new}
  done
  new="${part[*]}"
  echo -e "${new// /.}"
} 
version=`awk '{if(NR==7) print $0}' functions.php`
version=`echo "${version/Version: /}"`
version=`increment_version $version`
version="Version: $version"
printf $version
sed -i "7s/.*/$version/" functions.php
git add functions.php
git commit -m "$version" -m "";

sh .composer.sh


